/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 breakdancer.gltf --typescript 
*/

import React, {useRef} from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Breakdancer(props: any) {
    const group = useRef(null);
    const { nodes, materials } = useGLTF('./models/breakdance-boy/breakdancer.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[0, 2.447, -0.049]} scale={[1.244, 1.458, 1.458]}>
                <mesh geometry={nodes.Cylinder082_primitive0.geometry} material={materials['Upper.002']} />
                <mesh geometry={nodes.Cylinder082_primitive1.geometry} material={materials['Upper.003']} />
            </group>
            <PerspectiveCamera makeDefault={false} far={10000} fov={45.837} position={[-5.435, 1.618, -0.839]} rotation={[0, 1.364, 0]} />
            <mesh geometry={nodes.Cube075.geometry} material={materials['Skin.002']} position={[0, 2.964, 0]} />
            <mesh geometry={nodes.Cube076.geometry} material={materials['Trousers.003']} position={[0, 0.62, -0.01]} />
            <mesh geometry={nodes.Cube077.geometry} material={materials['Skin.002']} rotation={[0, 0, -0.516]} />
            <mesh geometry={nodes.Cube078.geometry} material={materials['Hair.001']} position={[0, 2.964, 0]} />
            <mesh geometry={nodes.Cube079.geometry} material={materials['Trousers.002']} position={[0, 1.221, -0.01]} />
            <mesh geometry={nodes.Cube080.geometry} material={materials['wHITE.002']} position={[0.001, 2.867, 0.172]} />
            <mesh geometry={nodes.Cube081.geometry} material={materials['wHITE.002']} position={[-0.001, 2.838, 0.166]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.Cylinder076.geometry} material={materials['wHITE.002']} position={[0.241, 0.347, -0.016]} rotation={[0, 0, 0.038]} />
            <mesh geometry={nodes.Cylinder077.geometry} material={materials['Upper.003']} position={[0, 2.447, -0.049]} scale={[1.244, 1.458, 1.458]} />
            <mesh geometry={nodes.Cylinder078.geometry} material={materials['Shoes.002']} position={[-0.255, 0.13, 0.121]} rotation={[Math.PI, 0.018, 0]} />
            <mesh geometry={nodes.Cylinder079.geometry} material={materials['wHITE.001']} position={[0.255, 0.039, 0.105]} />
            <mesh geometry={nodes.Cylinder080.geometry} material={materials['wHITE.001']} position={[-0.255, 0.039, 0.105]} />
            <mesh geometry={nodes.Cylinder081.geometry} material={materials['Shoes.002']} position={[0.255, 0.13, 0.121]} rotation={[0, 0.018, 0]} />
            <mesh geometry={nodes.Cylinder083.geometry} material={materials['Skin.002']} position={[0.183, 2.953, -0.036]} rotation={[1.522, -0.125, -0.6]} />
            <mesh geometry={nodes.Mball004.geometry} material={materials['Hair.001']} position={[0, 3.121, 0.163]} scale={0.043} />
            <mesh geometry={nodes.Plane028.geometry} material={materials['Leather.001']} position={[0.263, 0.235, 0.173]} rotation={[0.013, 0, -0.036]} />
            <mesh geometry={nodes.Plane029.geometry} material={materials['Hair.001']} position={[-0.065, 3.017, 0.169]} rotation={[1.722, -0.044, -0.26]} />
            <mesh geometry={nodes.Plane030.geometry} material={materials['Leather.001']} position={[-0.263, 0.235, 0.173]} rotation={[-3.129, 0, -0.036]} />
            <mesh geometry={nodes.Plane031.geometry} material={materials['Hair.001']} position={[0.065, 3.017, 0.169]} rotation={[1.722, -0.044, -0.26]} />
            <mesh geometry={nodes.Sphere017.geometry} material={materials['Eye.001']} position={[0.063, 2.973, 0.171]} rotation={[-0.054, 0.372, 0.004]} />
            <mesh geometry={nodes.Sphere019.geometry} material={materials['Eye.001']} position={[-0.063, 2.973, 0.171]} rotation={[-0.054, 0.372, 0.004]} />
        </group>
      )
}

useGLTF.preload('./models/breakdance-boy/breakdancer.gltf')
