/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 camera.gltf --typescript 
*/

import React, {useRef} from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Camera(props: any) {
    const group = useRef(null);
    const { nodes, materials } = useGLTF('./models/tripode/camera.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
          <group position={[0, 0.528, -0.101]} scale={0.913}>
            <mesh geometry={nodes.Cube001_primitive0.geometry} material={materials['Putih.001']} />
            <mesh geometry={nodes.Cube001_primitive1.geometry} material={materials['Merah ']} />
            <mesh geometry={nodes.Cube001_primitive2.geometry} material={materials['Hitam.001']} />
            <mesh geometry={nodes.Cube001_primitive3.geometry} material={materials['Biru Langit.001']} />
          </group>
          <group position={[0, 0.443, -0.121]} scale={0.913}>
            <mesh geometry={nodes.Cylinder005_primitive0.geometry} material={materials.Hitam} />
            <mesh geometry={nodes.Cylinder005_primitive1.geometry} material={materials['Putih.003']} />
          </group>
          <group position={[0, -0.342, -0.101]} rotation={[0, Math.PI / 2, 0]} scale={1.579}>
            <mesh geometry={nodes.Cylinder006_primitive0.geometry} material={materials['Putih.003']} />
            <mesh geometry={nodes.Cylinder006_primitive1.geometry} material={materials.Hitam} />
          </group>
          <PerspectiveCamera makeDefault={false} far={10000} fov={45.837} position={[2.662, -0.015, -0.021]} rotation={[Math.PI, -1.541, Math.PI]} />
          <mesh geometry={nodes.Circle.geometry} material={materials['Putih.003']} position={[0, 0.116, -0.101]} scale={1.579} />
          <mesh geometry={nodes.Circle001.geometry} material={materials['Putih.003']} position={[0, -0.626, -0.101]} scale={1.103} />
          <mesh geometry={nodes.Circle002.geometry} material={materials.Hitam} position={[0, -0.626, -0.101]} scale={[1.839, 1.446, 1.839]} />
          <mesh geometry={nodes.Cylinder004.geometry} material={materials['Putih.003']} position={[0, -0.125, -0.101]} scale={1.579} />
          <mesh geometry={nodes.NurbsPath.geometry} material={materials['Putih.003']} position={[0, -0.437, -0.101]} scale={1.579} />
        </group>
    )
}

useGLTF.preload('./models/tripode/camera.gltf')
