/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 valentine-couple-doing-dance.gltf --typescript
*/

import React, {useRef} from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function ValentineCouple(props: any) {
    const group = useRef(null);
    const { nodes, materials } = useGLTF('./models/married/valentine-couple-doing-dance.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[-0.231, 0, 0.258]} rotation={[-Math.PI, 1.402, -Math.PI]}>
                <mesh geometry={nodes.Cube008_primitive0.geometry} material={materials['Material.039']} />
                <mesh geometry={nodes.Cube008_primitive1.geometry} material={materials['Material.040']} />
            </group>
            <group position={[0.231, 0, 0.206]} rotation={[-Math.PI, 1.458, -Math.PI]} scale={0.874}>
                <mesh geometry={nodes.Cube015_primitive0.geometry} material={materials['Material.047']} />
                <mesh geometry={nodes.Cube015_primitive1.geometry} material={materials['Material.043']} />
            </group>
            <group position={[0.231, 0, 0.206]} rotation={[-Math.PI, 1.458, -Math.PI]} scale={0.874}>
                <mesh geometry={nodes.Cube016_primitive0.geometry} material={materials['Material.047']} />
                <mesh geometry={nodes.Cube016_primitive1.geometry} material={materials['Material.043']} />
            </group>
            <PerspectiveCamera makeDefault={false} far={10000} fov={45.837} position={[-2.774, 0.941, -0.306]} rotation={[0, 1.338, 0]} />
            <mesh geometry={nodes.Heart002.geometry} material={materials['Material.016']} position={[-0.198, 1.591, 0.051]} rotation={[0, -1.565, 0.548]} scale={0.071} />
            <mesh geometry={nodes.Heart001.geometry} material={materials['Material.016']} position={[-0.167, 0.819, -0.053]} rotation={[0.39, -0.973, 0.545]} scale={0.046} />
            <mesh geometry={nodes.Heart003.geometry} material={materials['Material.016']} position={[-0.162, 1.458, -0.313]} rotation={[0.353, -0.973, 0.545]} scale={0.046} />
            <mesh geometry={nodes.Heart004.geometry} material={materials['Material.016']} position={[-0.05, 1.771, 0.824]} rotation={[-0.779, -1.371, -1.219]} scale={0.071} />
            <mesh geometry={nodes.Heart005.geometry} material={materials['Material.016']} position={[0.49, 0.559, 0.57]} rotation={[0.353, -0.973, 0.545]} scale={0.046} />
            <mesh geometry={nodes.Heart006.geometry} material={materials['Material.016']} position={[0.134, 1.073, 1.02]} rotation={[0.353, -0.973, 0.545]} scale={0.046} />
            <mesh geometry={nodes.Cube004.geometry} material={materials['Material.036']} position={[-0.231, 0, 0.258]} rotation={[-Math.PI, 1.402, -Math.PI]} />
            <mesh geometry={nodes.Cube005.geometry} material={materials['Material.038']} position={[-0.231, 0, 0.258]} rotation={[-Math.PI, 1.402, -Math.PI]} />
            <mesh geometry={nodes.Cube006.geometry} material={materials['Material.037']} position={[-0.231, 0, 0.258]} rotation={[-Math.PI, 1.402, -Math.PI]} />
            <mesh geometry={nodes.Cube009.geometry} material={materials['Material.037']} position={[-0.231, 0, 0.258]} rotation={[-Math.PI, 1.402, -Math.PI]} />
            <mesh geometry={nodes.Cube010.geometry} material={materials['Material.041']} position={[-0.231, 0, 0.258]} rotation={[-Math.PI, 1.402, -Math.PI]} />
            <mesh geometry={nodes.Cube011.geometry} material={materials['Material.036']} position={[-0.231, 0, 0.258]} rotation={[-Math.PI, 1.402, -Math.PI]} />
            <mesh geometry={nodes.Cube001.geometry} material={materials['Material.042']} position={[0.231, 0, 0.206]} rotation={[-Math.PI, 1.458, -Math.PI]} scale={0.874} />
            <mesh geometry={nodes.Cube002.geometry} material={materials['Material.043']} position={[0.231, 0, 0.206]} rotation={[-Math.PI, 1.458, -Math.PI]} scale={0.874} />
            <mesh geometry={nodes.Cube003.geometry} material={materials['Material.044']} position={[0.231, 0, 0.206]} rotation={[-Math.PI, 1.458, -Math.PI]} scale={0.874} />
            <mesh geometry={nodes.Cube012.geometry} material={materials['Material.042']} position={[0.231, 0, 0.206]} rotation={[-Math.PI, 1.458, -Math.PI]} scale={0.874} />
            <mesh geometry={nodes.Cube013.geometry} material={materials['Material.046']} position={[0.231, 0, 0.206]} rotation={[-Math.PI, 1.458, -Math.PI]} scale={0.874} />
            <mesh geometry={nodes.Cube014.geometry} material={materials['Material.045']} position={[0.231, 0, 0.206]} rotation={[-Math.PI, 1.458, -Math.PI]} scale={0.874} />
        </group>
    )
}

useGLTF.preload('./models/married/valentine-couple-doing-dance.gltf')
