/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 woman-dancer.gltf --typescript 
*/

import React, {useRef} from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function WomanDancer(props: any) {
    const group = useRef(null);
  const { nodes, materials } = useGLTF('./models/dancer/woman-dancer.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.164, 2.172, -0.027]} rotation={[0.095, -0.671, -0.008]} scale={0.299}>
        <mesh geometry={nodes.Head_primitive0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Head_primitive1.geometry} material={materials['Material.010']} />
      </group>
      <PerspectiveCamera makeDefault={false} far={10000} fov={45.837} position={[-1.15, 1.185, -3.354]} rotation={[0, 0.356, 0]} />
      <mesh geometry={nodes.Cut_to_Size.geometry} material={materials['Material.002']} position={[-0.02, 1.534, -0.095]} rotation={[0.749, 1.146, -0.793]} scale={[1.321, 1.188, 1]} />
      <mesh geometry={nodes.Pants.geometry} material={materials['Material.002']} position={[0.055, 1.025, 0.041]} rotation={[0.166, 0.489, -0.339]} scale={0.982} />
      <mesh geometry={nodes.Shoes001.geometry} material={materials['Material.005']} position={[-0.051, 0.906, 0.067]} rotation={[1.406, 0.173, -0.634]} scale={[-0.47, 0.47, 0.346]}>
        <mesh geometry={nodes.Sole003.geometry} material={materials['Material.005']} position={[-0.001, -0.083, -0.085]} />
      </mesh>
      <mesh geometry={nodes.Shoes.geometry} material={materials['Material.005']} position={[0.152, 0.083, -0.107]} rotation={[0.007, 0.592, 0.029]} scale={[0.47, 0.47, 0.346]}>
        <mesh geometry={nodes.Sole002.geometry} material={materials['Material.005']} position={[0.001, -0.077, -0.09]} />
      </mesh>
      <mesh geometry={nodes.Iron.geometry} material={materials['Material.006']} position={[0.055, 1.523, 0.043]} rotation={[0.166, 0.489, -0.339]} />
      <mesh geometry={nodes.Belt.geometry} material={materials['Material.007']} position={[-0.025, 1.538, -0.083]} rotation={[0.166, 0.489, -0.339]} scale={[0.991, 1, 1]} />
      <mesh geometry={nodes.Hair.geometry} material={materials['Material.014']} position={[0.199, 2.243, -0.063]} rotation={[0.095, -0.671, -0.008]} scale={0.303} />
      <mesh geometry={nodes.Tongue.geometry} material={materials['Material.012']} position={[0.11, 2.061, 0.029]} rotation={[0.095, -0.671, -0.008]} scale={0.302} />
      <mesh geometry={nodes.Teeth.geometry} material={materials['Material.013']} position={[0.106, 2.089, 0.038]} rotation={[0.095, -0.671, -0.008]} scale={0.331} />
      <mesh geometry={nodes.Hair016.geometry} material={materials['Material.014']} position={[0.215, 1.981, 0.092]} rotation={[-2.135, 0.459, -0.557]} scale={0.042} />
      <mesh geometry={nodes.Hair014.geometry} material={materials['Material.014']} position={[0.256, 2.064, -0.009]} rotation={[-2.02, 0.678, -0.338]} scale={0.042} />
      <mesh geometry={nodes.Hair013.geometry} material={materials['Material.014']} position={[0.218, 2.079, 0.047]} rotation={[-1.618, 0.55, -0.405]} scale={0.042} />
      <mesh geometry={nodes.Hair012.geometry} material={materials['Material.014']} position={[0.236, 1.984, 0.063]} rotation={[-2.135, 0.459, -0.557]} scale={0.042} />
      <mesh geometry={nodes.Hair011.geometry} material={materials['Material.014']} position={[0.222, 1.99, 0.069]} rotation={[-2.135, 0.459, -0.557]} scale={0.042} />
      <mesh geometry={nodes.Hair010.geometry} material={materials['Material.014']} position={[0.29, 2.198, -0.034]} rotation={[-2.554, 0.108, -0.099]} scale={0.041} />
      <mesh geometry={nodes.Hair009.geometry} material={materials['Material.014']} position={[0.287, 2.205, -0.055]} rotation={[-2.555, -0.047, -0.017]} scale={0.042} />
      <mesh geometry={nodes.Hair008.geometry} material={materials['Material.014']} position={[0.281, 2.21, -0.075]} rotation={[-2.493, -0.452, 0.219]} scale={0.042} />
      <mesh geometry={nodes.Hair007.geometry} material={materials['Material.014']} position={[0.255, 2.218, -0.1]} rotation={[-2.443, -0.585, 0.317]} scale={0.042} />
      <mesh geometry={nodes.Hair006.geometry} material={materials['Material.014']} position={[0.262, 2.241, -0.033]} rotation={[-2.452, 0.586, -0.397]} scale={0.042} />
      <mesh geometry={nodes.Hair005.geometry} material={materials['Material.014']} position={[0.24, 2.241, -0.003]} rotation={[-2.29, 0.529, -0.483]} scale={0.042} />
      <mesh geometry={nodes.Hair004.geometry} material={materials['Material.014']} position={[0.215, 2.233, 0.02]} rotation={[-2.135, 0.459, -0.557]} scale={0.042} />
      <mesh geometry={nodes.Hair003.geometry} material={materials['Material.014']} position={[0.208, 2.231, 0.045]} rotation={[-2.135, 0.459, -0.557]} scale={0.042} />
      <mesh geometry={nodes.Hair002.geometry} material={materials['Material.014']} position={[0.187, 2.197, 0.069]} rotation={[-2.135, 0.459, -0.557]} />
      <mesh geometry={nodes.Hair001.geometry} material={materials['Material.014']} position={[0.188, 2.217, 0.066]} rotation={[-2.135, 0.459, -0.557]} scale={0.042} />
      <mesh geometry={nodes.Hair015.geometry} material={materials['Material.015']} position={[0.248, 2.057, 0.026]} rotation={[-1.205, -0.953, -0.247]} scale={[0.041, 0.031, 0.041]} />
      <mesh geometry={nodes.Eyebrow.geometry} material={materials['Material.014']} position={[0.104, 2.204, 0.049]} rotation={[1.733, -0.031, 0.959]} />
      <mesh geometry={nodes.Eyes.geometry} material={materials['Material.016']} position={[0.104, 2.168, 0.049]} rotation={[0.098, -0.325, -0.007]} scale={0.328} />
      <mesh geometry={nodes.Ears.geometry} material={materials['Material.009']} position={[0.169, 2.154, -0.035]} rotation={[-0.056, -0.665, -0.102]} scale={0.227} />
      <mesh geometry={nodes['T-Shirt'].geometry} material={materials['Material.017']} position={[0.099, 1.829, -0.061]} rotation={[0.166, 0.489, -0.339]} />
      <mesh geometry={nodes.Ring.geometry} material={materials['Material.006']} position={[0.05, 1.524, 0.04]} rotation={[1.573, -0.298, -0.513]} scale={1.216} />
      <mesh geometry={nodes.Iron001.geometry} material={materials['Material.006']} position={[0.044, 1.525, 0.043]} rotation={[0.388, 0.886, -2.054]} scale={0.375} />
      <mesh geometry={nodes.Body.geometry} material={materials['Material.001']} position={[0.142, 1.581, 0.162]} rotation={[0.166, 0.489, -0.339]} />
    </group>
  )
}

useGLTF.preload('./models/dancer/woman-dancer.gltf')
